In [2]:
import pandas as pd

dados = {
    "vendedor": [
        "Ana", "Ana", "Ana",
        "Bruno", "Bruno", "Bruno",
        "Carlos", "Carlos", "Carlos", "Ana"
    ],
    
    "cidade": [
        "Salvador", "Lauro de Freitas", "Salvador",
        "Salvador", "Lauro de Freitas", "Salvador",
        "Lauro de Freitas", "Salvador", "Lauro de Freitas",
        "Lauro de Freitas"
    ],
    
    "categoria": [
        "Eletrônicos", "Acessórios", "Eletrônicos",
        "Acessórios", "Eletrônicos", "Eletrônicos",
        "Acessórios", "Eletrônicos", "Acessórios", "Eletrônicos"
    ],
    
    "produto": [
        "Notebook", "Mouse", "Monitor",
        "Teclado", "Notebook", "Monitor",
        "Mouse", "Notebook", "Teclado", "Notebook"
    ],
    
    "total": [
        3500, 150, 1200,
        200, 3200, 1100,
        180, 3000, 250, 3400
    ]
}

dataframe = pd.DataFrame(dados)
dataframe

  vendedor            cidade    categoria   produto  total
0      Ana          Salvador  Eletrônicos  Notebook   3500
1      Ana  Lauro de Freitas   Acessórios     Mouse    150
2      Ana          Salvador  Eletrônicos   Monitor   1200
3    Bruno          Salvador   Acessórios   Teclado    200
4    Bruno  Lauro de Freitas  Eletrônicos  Notebook   3200
5    Bruno          Salvador  Eletrônicos   Monitor   1100
6   Carlos  Lauro de Freitas   Acessórios     Mouse    180
7   Carlos          Salvador  Eletrônicos  Notebook   3000
8   Carlos  Lauro de Freitas   Acessórios   Teclado    250
9      Ana  Lauro de Freitas  Eletrônicos  Notebook   3400

In [3]:
produto_fat_cidade = pd.pivot_table(dataframe,index="produto",values="total",columns="cidade",aggfunc = ("sum"))
produto_fat_cidade

cidade    Lauro de Freitas  Salvador
produto
Monitor                NaN    2300.0
Mouse                330.0       NaN
Notebook            6600.0    6500.0
Teclado              250.0     200.0

In [4]:
cidade_faturamento_quantidade = dataframe.groupby("cidade").agg(total_vendido=("total","sum"),quantidade_total=("produto","count")).reset_index().sort_values(by="total_vendido",ascending=False)
cidade_faturamento_quantidade

             cidade  total_vendido  quantidade_total
1          Salvador           9000                 5
0  Lauro de Freitas           7180                 5

In [5]:
vendedor_faturamento_categoria = dataframe.groupby(["vendedor","categoria"]).agg(total_vendido=("total","sum")).reset_index().sort_values(by="total_vendido",ascending=False)
vendedor_faturamento_categoria

  vendedor    categoria  total_vendido
1      Ana  Eletrônicos           8100
3    Bruno  Eletrônicos           4300
5   Carlos  Eletrônicos           3000
4   Carlos   Acessórios            430
2    Bruno   Acessórios            200
0      Ana   Acessórios            150